### ISSUE TITLE
Feature proposal: boolean parameter for standard formatting

### ISSUE THREAD

**Issue by vreuter** [databio/logmuse#17]
The default format in `init_logger` now truncates level names. Can there be an opt-in parameter to use the standard, non-truncated format?

**Comment by nsheff** [comment]
Sure! I think I did that just to make them all the same width, which seemed to look better when lots are printed in a row. Do you not like the truncation?

**Comment by vreuter** [comment]
Yeah I figured it may be something to do with standardizing for rendering downstream like in HTML, or just for personal preference in the terminal. I do like the full names a little better, but it's not a big deal. I may go ahead and add this and open a PR, though, if you'd be alright with it.
