### ISSUE TITLE
Supported versions on PyPI are old

### ISSUE THREAD

**Issue by vreuter** [databio/logmuse#25]
2.7, 3.5, and 3.6 are listed as supported versions on PyPI, but this appears to work for more recent versions of Python. The CI matrix and the `setup.py` could be updated.

**Comment by khoroshevskyi** [comment]
Can we updated versions to 3.8 -3.12 ? 
We can't install logmuse in Python 3.8, because logmuse doesn't support that version

**Comment by nsheff** [comment]
yes, please update
