### ISSUE TITLE
downgrade info

### ISSUE THREAD

**Issue by nsheff** [databio/logmuse#4]
can this be moved to `debug`?

https://github.com/databio/logmuse/blob/b7e712c225b164d0783e42a20624b0d41c3cfe7d/logmuse/est.py#L236-L237

typical user is (and should be) completely unaware of logmuse

in general I favor as few printouts as possible in the default use case.

**Comment by nsheff** [comment]
I also can't find the source of this message:

`No handlers could be found for logger "looper.project"`in any repository but it should also be downgraded... what is emitting that message (in caravel)?

**Comment by vreuter** [comment]
It's emitted from `logging` itself when a call is made on a logger with no handlers.
